---
  - name: Playbook
    hosts: ec2
    user: ubuntu
    become: yes
    become_user: root
    vars:
      - ansible_host_key_checking: false
    tasks:
    - name: "Set hostname to AnsibleFTW"
      hostname:
        name: ansibleftw
    - name: "Set DNS servers"
      net_system:
        name_servers:
          - 8.8.8.8
          - 8.8.4.4
