--- 
- 
  become: true
  become_user: root
  hosts: ec2
  user: ubuntu
  name: Playbook
  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  vars: 
    - 
      ansible_host_key_checking: false
